package lk.steam.rms.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lk.steam.rms.entity.MailStructure;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.stereotype.Service;

@Service
@EnableAsync
public class MailService {
    @Autowired
    private JavaMailSender javaMailSender;

    @Value("${spring.mail.username}")
    private String username;

    @Async
    public void sendMail(String mail, MailStructure mailStructure) {
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom(username);
        message.setSubject(mailStructure.getSubject());
        message.setText(mailStructure.getMessage());
        message.setTo(mail);
        javaMailSender.send(message);
    }

    @Async
    public void sendOTPMail(String mail,String otp) throws MessagingException {
        MimeMessage message = javaMailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message,true,"UTF-8");

        helper.setFrom(username);
        helper.setTo(mail);
        helper.setSubject("Password Reset 🔑 [OTP Confirmation]");
        String msgContent = "<body style='margin: 0;padding: 0;display:flex;width:100%;height:100vh;align-items:center;justify-content:center;font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif'>" +
                "    <div style='width: 100%;max-width: 550px;margin: 0 auto;background-color: #ffffff;border-radius: 8px;border: 1px solid #f1f1f1;overflow: hidden;box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);'>" +
                "        <div  style='margin-left: 20px;border-bottom: 1px solid #f1f1f1;display: flex;align-items: center;justify-content: space-between;'>" +
                "            <img src='https://i.ibb.co/4VYLzvG/icon-sq.png' width='60px'>" +
                "            <h2 style='margin-right: 20px;'>STEAM Password Assistance</h2>" +
                "        </div>" +
                "        <div style='padding: 20px;'>" +
                "            We received a request to reset your password. &nbsp;Your One-Time Password (OTP) for password reset is : " +
                "            <div style='display: block;width: fit-content;font-size: 24px;font-weight: bold;margin-top: 5px;margin-bottom: 5px;'>"+otp+"</div>" +
                "            Please enter this OTP to reset your password. &nbsp;This code is valid for the next 5 minutes." +
                "            <br><br>" +
                "            If you did not request a password reset, please ignore this email." +
                "           <p style='font-size: medium;color: #999999;text-align: center;margin-top: 20px'>This is an autogenerated email. Please don't reply</p>" +
                "        </div>" +
                "    </div>" +
                "</body>";
        helper.setText(msgContent, true); // true indicates HTML

        javaMailSender.send(message);

    }
}
